### ISSUE TITLE
[BUG] Warning thrown by `url_stat` when file does not exist

### ISSUE THREAD

**Issue by romm** [dg/bypass-finals#1]
When `\DG\BypassFinals::url_stat` is called with the path of a file that does not exist on the filesystem, a warning is thrown: `stat(): stat failed for /path/to/my/unexisting/file`.

A check should be done before calling the native method with an invalid path.

**Comment by dg** [comment]
Why it is a bug?

**Comment by romm** [comment]
In my case (if I understood correctly the source of the issue), a statement like `class_exists('PSR4/Path/To/Unexisting/Class')` calls Composer autoloader which probably tries to get information from an unexisting file.

I might take a deeper look at it if you want me to. :)

**Comment by dg** [comment]
If the original function generates a warning, it makes sense to me that url_stat() generates the same warning too.

**Comment by romm** [comment]
Hello @dg,

Indeed, I fully agree with what you said. I've been rushing for a solution for my case, sorry. 🙂 

I've been seeking for more information, I can confirm that the statement that generates the warning is here: [Composer/Autoload/ClassLoader:384](https://github.com/composer/composer/blob/1.5.2/src/Composer/Autoload/ClassLoader.php#L384)

I also discovered that [`streamWrapper::url_stat()` is called in response to all `stat()` related functions, such as `file_exists()`](http://php.net/manual/en/streamwrapper.url-stat.php). Unfortunately I have no idea what could be done next. Could you help on this?

For your information, this is the piece of code that throws the warning: [Prophecy/PhpDocumentor/ClassAndInterfaceTagRetriever.php:34](https://github.com/phpspec/prophecy/blob/v1.7.2/src/Prophecy/PhpDocumentor/ClassAndInterfaceTagRetriever.php#L34)

**Comment by dg** [comment]
Thanks for describing the problem. I've already found a solution.

**Comment by romm** [comment]
Perfect, the issue is fixed by my side. Thank you! 😉

**Comment by Mediagone** [comment]
I also have this problem with the last version. Have you fixed it yet? Thanks!

**Comment by Mediagone** [comment]
I got the same problem (with v1.0 & dev-master), is it fixed yet? Thanks!
