### ISSUE TITLE
"final" is not case-sensitive

### ISSUE THREAD

**Issue by ayg** [dg/bypass-finals#11]
```
$ php -r 'FINAL class A {} class B extends A {}'
PHP Fatal error:  Class B may not inherit from final class (A) in Command line code on line 1
```
removeFinals does
```php
if (strpos($code, 'final') !== false) {
```
This will skip a file where all the "final"s are not lowercase. I don't think anyone actually does this, but I think this should be stripos instead of strpos, anyway.

(Not tested, just code inspection.)

**Comment by dg** [comment]
fixed
