### ISSUE TITLE
What happens when using an opcode cache?

### ISSUE THREAD

**Issue by ayg** [dg/bypass-finals#12]
I don't know if this is really an "issue" so much as a question. But it seems worth documenting either way, so I'll claim it's a documentation request.

How does this interact with opcode caches like APC? If on one request a PHP file gets cached with finals not removed, and then another request comes along and tries to load the file with finals removed, is the parsed file going to get served from cache with finals still in it? I.e., you'll get files randomly with or without final depending on which one got cached? Or is this avoided somehow?

**Comment by dg** [comment]
It seems it works even when the file is in cache, but I only tried it with OPcache and it is possible that in other systems and versions it may behave differently.
