### ISSUE TITLE
setWhitelist() undefined

### ISSUE THREAD

**Issue by mattfletcher** [dg/bypass-finals#13]
`PHP Fatal error:  Uncaught Error: Call to undefined method DG\BypassFinals::setWhitelist() `

Running 1.1.2, the code sample in the README fails as the method doesn't exist.

**Comment by mattfletcher** [comment]
Ah, it's in master, but not 1.1.2. Could a new release be made?

**Comment by Nyholm** [comment]
How about releasing 1.2?

**Comment by dg** [comment]
Version 1.2 has been released. Unlike the master, it uses the fnmatch function to match paths, so wildchars are used in the whitelist.
