### ISSUE TITLE
TypeError: touch() expects parameter 2 to be int, null given

### ISSUE THREAD

**Issue by KartaviK** [dg/bypass-finals#18]
I catch specific internal exception in dev-master branch

```bash
TypeError: touch() expects parameter 2 to be int, null given
```

**Comment by dg** [comment]
It is expected behavior https://3v4l.org/XIe8v

**Comment by KartaviK** [comment]
I understand that. But i see this exception in magic case (often when running `phpunit` after `composer install`) and after that everything works properly. So sometimes i need run `phpunit` two times for correct work.

**Comment by phcorp** [comment]
> It is expected behavior https://3v4l.org/XIe8v

@dg the problem even occurs when using touch without second argument. Missing optional touch arguments are added in `BypassFinals::stream_metadata` (initialized as null)

**Comment by dg** [comment]
@phcorp I see
