### ISSUE TITLE
Class with __invoke cannot be mocked

### ISSUE THREAD

**Issue by sergiz** [dg/bypass-finals#22]
Hello.

I ran across a problem when I use a class that only has a __invoke method.  It complains that such class is marked final and cannot be mocked. If I use a normal method then the problem disappears.

Is there something I can do about that?

**Comment by dg** [comment]
I can't simulate such a situation. When I change the method name to `__invoke` in this test, it still works fine. https://github.com/dg/bypass-finals/blob/master/tests/BypassFinals/fixtures/final.class.php#L8

**Comment by sergiz** [comment]
I can confirm that it is indeed working. Not sure why the problem occured back then.
