### ISSUE TITLE
Failed infection test if bypass-final is enabled

### ISSUE THREAD

**Issue by Pablossoo** [dg/bypass-finals#29]
Hello, I am using the library for infection testing https://infection.github.io/guide/ and if the bypass-final library is enabled the infections are not working as expected - the coverage test is not working properly.
example;
the case where bypass is disabled;
100% coverage of infection

the case where the bypass is enabled;
20-30% coverage.

Could you please take a look at what might be wrong?

**Comment by JanTvrdik** [comment]
https://github.com/dg/bypass-finals/issues?q=infection

**Comment by dkarlovi** [comment]
Duplicate of #9.

**Comment by dkarlovi** [comment]
#9 was closed, this can be closed too AFAIK.
