### ISSUE TITLE
Segmentation fault with 1.4.0 when running phpunit with code coverage

### ISSUE THREAD

**Issue by svnldwg** [dg/bypass-finals#35]
After upgrading to version 1.4.0 I get an error when running this command:

`php -dxdebug.mode=coverage bin/phpunit`

The error:
```
PHPUnit 9.5.24 #StandWithUkraine

Testing 
.Segmentation fault
```

This only occurs on 1.4.0, with version 1.3.1 everything works fine.

**Comment by that-guy-iain** [comment]
I also get this error. When xdebug is enabled it says there is an infinite loop.

And it doesn't depend on a specific test, if I choose to test just a subsection of tests, it'll still fail just on a different test.

```
PHPUnit 9.5.24 #StandWithUkraine

...EEEEEEEE.....................................EXdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames
```

**Comment by dextacy10-13** [comment]
We also had this

**Comment by dg** [comment]
Can you verify the fix?

**Comment by that-guy-iain** [comment]
I can confirm it's fixed.

**Comment by shyim** [comment]
With the fix, is blackfire broken. It segfaults without running even a trace.
I am in contact with the support to find the root cause. just fyi if you having it locally also 😅
