### ISSUE TITLE
Support bypass readonly in PHP 82

### ISSUE THREAD

**Issue by Myks92** [dg/bypass-finals#39]
In PHP 82, it is now possible to mark classes "readonly". However, tests of such classes give an error: "Class "Password Hasher" is declared "readonly" and cannot be duplicated". I would like this library to be able to fix these errors as well.

Fixtures:

```php
final readonly class FinalClass
{
}
```

**Comment by Ilyes512** [comment]
This would also help mocking final readonly classes, because you get the following error when you try to mock it:

```
Fatal error: Non-readonly class Mockery_0_SomeClass cannot extend readonly class AnotherClass in /src/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code on line 30
```

**Comment by Myks92** [comment]
I found a library that solves this problem: https://github.com/zoltanka/bypass-readonly . Now you can use it, but in the future I would like to have support in the original library.

**Comment by jg-development** [comment]
+1 plz

**Comment by jg-development** [comment]
@Myks92 maybe add a pull request .... could make it easier for @dg

**Comment by jg-development** [comment]
thx for the quick work ... with the new tag I can mock again

**Comment by Ilyes512** [comment]
Oh nice :) Thx @dg!

**Comment by dg** [comment]
@jg-development please try this master, if it works I will tag a new version

**Comment by jg-development** [comment]
tested and works with master + prophecy

```php
        BypassFinals::enable();
        
        $deliveryFilter = $this->prophesize(DeliveryFilter::class);
        
        $deliveryFilter->__toString()->willReturn('123123');
        $deliveryFilter = $deliveryFilter->reveal();

        $queryString = (string) $deliveryFilter;
```

**Comment by dg** [comment]
Yeah, it removes readonly everywhere in the code.

**Comment by lucascesconetto** [comment]
@dg Is it possible to configure whether or not I want to use this readonly bypass feature ??

First point is that this broke codes, we have libs that check if the properties are readonly based on reflection, and with this feature that you added, it broke these codes, I understand that this should be configurable or at least have entered as a "Major" .

**Comment by andrevitor103** [comment]
> @dg Is it possible to configure whether or not I want to use this readonly bypass feature ??
> 
> First point is that this broke codes, we have libs that check if the properties are readonly based on reflection, and with this feature that you added, it broke these codes, I understand that this should be configurable or at least have entered as a "Major" .
> 
> Another reason I see this feature being optional and configurable is that in some cases we want to ensure immutability. And the way it is enabled by default today, it is not possible to have that guarantee.

Hello everyone, I opened this PR with a suggestion on how to solve this problem. If you can look into it, thank you. [[PR](https://github.com/dg/bypass-finals/pull/41)]
