### ISSUE TITLE
Doesn't work with amphp/process

### ISSUE THREAD

**Issue by ostrolucky** [dg/bypass-finals#40]
See https://github.com/amphp/process/issues/67

Produces `Errno: 2; fseek(): Stream does not support seeking`

**Comment by JanTvrdik** [comment]
Really, not even callstack?

**Comment by ostrolucky** [comment]
Reproducer was given in linked story

**Comment by dg** [comment]
Closing due to lack of context

**Comment by ostrolucky** [comment]
I am happy to provide more context. What info specifically are you missing? amphp/process is a package used by various libraries, one of them eg. https://github.com/pact-foundation/pact-php/tree/9.1.1. If you enable dg/bypass-finals in your bootstrap.php, these tools do not work with mysterious errors like fseek() above.

**Comment by dg** [comment]
I could use some minimal code, maybe a repository, that I could download and immediately see the error.

**Comment by riki137** [comment]
I had quite a trouble searching for this problem on the internet, i'd like to at least attach the full error:

```
There was 1 error:

1) Tests\...::...
Amp\Process\ProcessException: Process could not be started: Errno: 2; fseek(): Stream does not support seeking

.../vendor/amphp/process/src/Internal/Posix/PosixRunner.php:56
.../vendor/dg/bypass-finals/src/NativeWrapper.php:148
.../vendor/dg/bypass-finals/src/MutatingWrapper.php:90
.../vendor/amphp/process/src/Internal/Posix/PosixRunner.php:60
.../vendor/amphp/process/src/Process.php:76
.../tests/Integration/....php:23
```

Would be great if the error message would be in the title as well, because the error message itself does not help solve the problem at all.
