### ISSUE TITLE
Getting this on running my tests.

### ISSUE THREAD

**Issue by Abraham-Flutterwave** [dg/bypass-finals#42]
Invalid callback Monolog\Handler\RotatingFileHandler::customErrorHandler, cannot access private method Monolog\Handler\RotatingFileHandler::customErrorHandler()

  at vendor/dg/bypass-finals/src/NativeWrapper.php:206

**Comment by Abraham-Flutterwave** [comment]
@dg please assist

**Comment by dg** [comment]
I don't understand what you're writing here at all.

**Comment by Abraham-Flutterwave** [comment]
thanks @dg for your help
