### ISSUE TITLE
Warnings converted to ErrorExceptions make url_stat fail on non-existent files

### ISSUE THREAD

**Issue by pawelabrams** [dg/bypass-finals#44]
Within my setup (Symfony 6.3, PHP 8.2, phpunit 9.6) there is by default an error handler that changes all errors and warnings into ErrorExceptions. This causes current version of `NativeWrapper::url_stat` to let this exception bubble to framework's code which doesn't expect functions like `file_exists` to fail.

The error handler cannot be trivially turned off, and I suspect the codebase I maintain isn't the only one which has this default. The problem is not fixed by error silencing operator, as per the docs `If a custom error handler function is set with set_error_handler(), it will still be called even though the diagnostic has been suppressed.` (https://www.php.net/manual/en/language.operators.errorcontrol.php)

I propose to add another catch to the try added in #34 (see bug #31). I'll post a PR shortly.

Expected: file_exists to always return a boolean.
Current behaviour:
```
Test Name (Test\Path)
 ✘ 
   ┐
   ├ ErrorException: stat(): stat failed for /var/www/html/config/secrets/test/test.list.php
   │
   ╵ /var/www/html/vendor/dg/bypass-finals/src/NativeWrapper.php:206
   ╵ /var/www/html/vendor/dg/bypass-finals/src/NativeWrapper.php:193
   ╵ /var/www/html/vendor/dg/bypass-finals/src/BypassFinals.php:192
   ╵ /var/www/html/vendor/symfony/framework-bundle/Secrets/SodiumVault.php:153
...
```

**Comment by dg** [comment]
A correctly written error handler must check error_reporting() and thus the `@` operator:

```php
		set_error_handler(function (int $severity, string $message, string $file, int $line) {
			if (error_reporting() & $severity) {
				throw new \ErrorException($message, 0, $severity, $file, $line);
			}
		});
```

**Comment by pawelabrams** [comment]
You are right; the problem was in one of the projects libraries.

Sorry for wasting your time! I solemnly vow to never create issues before coffee again.

**Comment by dg** [comment]
:-)
