### ISSUE TITLE
Cannot bootstrap extension because class DG\BypassFinals\PHPUnitExtension does not exist

### ISSUE THREAD

**Issue by olexoliinyk0** [dg/bypass-finals#51]
This is the WARNing message that you get after following the steps from `master`'s README -- especially the part about "registering BypassFinals in PHPUnit 10" - it makes you think that that class is already in the Released version (which is not specified in "install is through Composer" part), but it actually exists only in the master branch. 

Please, add it to the next Release or specify that one should add `composer require dg/bypass-finals:dev-master --dev` to use that extensions->bootstrap class. Thanks!

**Comment by dg** [comment]
I've tagged the new version, it should work now.
