### ISSUE TITLE
stat(): stat failed for

### ISSUE THREAD

**Issue by caiovncius** [dg/bypass-finals#52]
Hello everyone,

I'm using this package in my Laravel project. But, after I did add this extension in the phpunit.xml file, all my tests is showing one warning:

`stat(): stat failed for /var/www/html/`

Should I make some configuration for that?

**Comment by clementlanot** [comment]
Same issue for me with Laravel 11

**Comment by davideprevosto** [comment]
Same issue for me on Laravel 10. I am using https://github.com/nunomaduro/mock-final-classes (it's using https://github.com/dg/bypass-finals).

`stat(): stat failed for /Users/encodia/Sviluppo/www/project/vendor/composer/../fakerphp/faker/src/Faker/Provider/en_US/Barcode.php`

**Comment by MarcoLeko** [comment]
I get a similar error in a symfony project using phpunit version 9.5: This time in the NativeWrapper.php:206 
```Caused by
ErrorException: stat(): stat failed for /app/vendor/composer/../jsmdg/event-schema/src/PHPUnit/Framework/TestFailure.php in /app/vendor/dg/bypass-finals/src/NativeWrapper.php:206
```
