### ISSUE TITLE
`mkdir` method always uses non-recursive flag

### ISSUE THREAD

**Issue by romm** [dg/bypass-finals#8]
The third parameter of `mkdir` is a boolean which indicates if the given folder path should be created recursively.

However, `false` is always given; so when some API tries to create a full path, it fails.

https://github.com/dg/bypass-finals/blob/06d98c87299ce5fa6b0fc709cabdfa7ca2d04576/src/BypassFinals.php#L54-L57

---

My usecase is: I want to use [Infection](https://github.com/infection/infection) which needs to have access to PHPUnit's coverage files, which are created in a folder (which is itself created with the recursive parameter set to `true`); see [php-code-coverage Facade file](https://github.com/sebastianbergmann/php-code-coverage/blob/618da943956c06d0c35d63730872952395a0e1ea/src/Report/Xml/Facade.php#L285).

So when I try to run Infection, the coverage files creation fails because the folders can't be created.

---

I tried to look what value is given to the `$options` parameters of the method above. [Documentation says it can contain `STREAM_MKDIR_RECURSIVE`](https://secure.php.net/manual/en/streamwrapper.mkdir.php), which would be a solution.

In my case it contains `9` [which seems to be the equivalent of `STREAM_NOTIFY_FAILURE`](https://secure.php.net/manual/en/stream.constants.php).

I don't know how to fix it with these information, any idea? 🙂

**Comment by romm** [comment]
That was fast!

Thanks a lot, it works like a charm. 😄

**Comment by dg** [comment]
Your're welcome :)
